# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_IMAGE_NAME: "tomekskr/recipe-app"
  TMP_IMAGE_PATH: "/tmp/recipe-app.tar"
jobs:
  go_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd src
        go build -v ./...

    - name: Test
      run: echo "dummy testing"
  docker_build:
    runs-on: ubuntu-latest
    needs: go_build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: src/
        tags: ${{ env.BUILD_IMAGE_NAME }}:latest
        outputs: type=docker,dest=/tmp/recipe-app.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BUILD_IMAGE_NAME }}
        path: ${{ env.TMP_IMAGE_PATH }}
  docker_push:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.TMP_IMAGE_PATH }}
          path: /tmp
      - name: Load image
        run: |
          docker load --input ${{ env.TMP_IMAGE_PATH }}
          docker image ls -a       
