name: Go

on:
  push:
    branches: [ "master","dev","staging" ]
  pull_request:
    branches: [ "master","dev","staging" ]

env:
  IMAGE_NAME: "recipe-app"
  BUILD_IMAGE_NAME: "tomekskr/recipe-app"
  TMP_IMAGE_PATH: "/tmp/artifacts/recipe-app.tar"
jobs:
  go_build:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd src
        go build -v ./...
  go_test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: go_build
    steps:
    - name: Test
      run: echo "dummy testing"
  docker_build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: go_build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - run: mkdir -p /tmp/artifacts
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: src/
        tags: ${{ env.BUILD_IMAGE_NAME }}:latest,${{ env.BUILD_IMAGE_NAME }}:${{ github.ref_name }}-latest,
        outputs: type=docker,dest=/tmp/artifacts/recipe-app.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.IMAGE_NAME }}
        path: ${{ env.TMP_IMAGE_PATH }}
        
  docker_push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: docker_build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.TMP_IMAGE_PATH }}
      - name: Load image
        run: |
          ls -la /tmp/
          ls -la /tmp/artifacts
          docker load -i ${{ env.TMP_IMAGE_PATH }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push -a
